Repository DeveloperAcademy-POSTECH/MC2-Team9-MUSE, pull requests merged in 2022-06, with the labels that each got.

#17 Wonny3
  Muse/Muse.xcodeproj/project.pbxproj
  Muse/Muse/Auth/Login/LoginView.swift
  Muse/Muse/MakeTicket/MakeTicketView.swift
  Muse/Muse/MuseApp.swift
  Muse/Muse/MusicSeach/ArtworkLoader.swift
  Muse/Muse/MusicSeach/MusicSearchApp.swift
  Muse/Muse/MusicSeach/MusicSearchView.swift
  Muse/Muse/MusicSeach/SearchDataModel.swift
  Muse/Muse/MusicSeach/SongListViewModel.swift
  Muse/Muse/MusicSeach/TicketWritingView.swift
Labels: enhancement

#24 Zero
  Muse/Muse/MakeTicket/MakeTicketView.swift
  Muse/Muse/MusicSeach/MusicSearchView.swift
Labels: bug

#38 [bug] : 티켓 작성 완료 후, 작성한 값이 남아있는 버그 수정
  Muse/Muse/Base/AuthTextField.swift
  Muse/Muse/MakeTicket/MakeTicketView.swift
Labels: bug

#41 Zero userdown
  Muse/Muse/Auth/Resister/RegistrationService.swift
  Muse/Muse/Auth/Session/SessionService.swift
  Muse/Muse/Main/MainView.swift
  Muse/Muse/Main/TicketView.swift
  Muse/Muse/MakeTicket/MakeTicketView.swift
  Muse/Muse/MyPage/MyPageView.swift
  Muse/Muse/MyPage/TicketListView.swift
Labels: documentation

#42 [bug] : 애니메이션 중첩버그 해결
  Muse/Muse/Main/MainView.swift
Labels: bug

#39 Ayden modify design2
  Muse/Muse/Auth/Login/LoginView.swift
  Muse/Muse/Auth/Resister/ResisterView.swift
  Muse/Muse/Main/MainView.swift
  Muse/Muse/Main/TicketMachineView.swift
  Muse/Muse/Main/TicketView.swift
  Muse/Muse/MakeTicket/MakeTicketView.swift
  Muse/Muse/MusicSeach/MusicSearchView.swift
  Muse/Muse/MyPage/MyPageView.swift
  Muse/Muse/MyPage/TicketListView.swift
Labels: documentation

#53 music Url
  Muse/Muse/Main/TicketView.swift
  Muse/Muse/MakeTicket/MakeTicketView.swift
Labels: enhancement
